---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}_{{ ansible_distribution_minor_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}_{{ ansible_distribution_minor_version }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: OPENLDAP | Assert that the OS is supported
  assert:
    that: openldap_os_supported == true
  tags:
    - openldap

- name: OPENLDAP | Installation
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ openldap_packages}} "

- name: OPENLDAP | Configuration
  template:
    src: ldap.conf.j2
    dest: "{{ openldap_configuration_file }}"
    owner: root
    group: root
    mode: 0644
